INSERT into smash_character(name) VALUES ("bayonetta");
INSERT into smash_character(name) VALUES ("bowserjr");
INSERT into smash_character(name) VALUES ("captain");
INSERT into smash_character(name) VALUES ("charizard");
INSERT into smash_character(name) VALUES ("cloud");
INSERT into smash_character(name) VALUES ("corrin");
INSERT into smash_character(name) VALUES ("darkpit");
INSERT into smash_character(name) VALUES ("dedede");
INSERT into smash_character(name) VALUES ("diddy");
INSERT into smash_character(name) VALUES ("donkey");
INSERT into smash_character(name) VALUES ("drmario");
INSERT into smash_character(name) VALUES ("duckhunt");
INSERT into smash_character(name) VALUES ("falco");
INSERT into smash_character(name) VALUES ("fox");
INSERT into smash_character(name) VALUES ("gamewatch");
INSERT into smash_character(name) VALUES ("gannondorf");
INSERT into smash_character(name) VALUES ("grabchar");
INSERT into smash_character(name) VALUES ("greninja");
INSERT into smash_character(name) VALUES ("ike");
INSERT into smash_character(name) VALUES ("jigglypuff");
INSERT into smash_character(name) VALUES ("kirby");
INSERT into smash_character(name) VALUES ("link");
INSERT into smash_character(name) VALUES ("littlemac");
INSERT into smash_character(name) VALUES ("lucario");
INSERT into smash_character(name) VALUES ("lucas");
INSERT into smash_character(name) VALUES ("lucina");
INSERT into smash_character(name) VALUES ("luigi");
INSERT into smash_character(name) VALUES ("mario");
INSERT into smash_character(name) VALUES ("marth");
INSERT into smash_character(name) VALUES ("megaman");
INSERT into smash_character(name) VALUES ("metaknight");
INSERT into smash_character(name) VALUES ("mewtwo");
INSERT into smash_character(name) VALUES ("miifighter");
INSERT into smash_character(name) VALUES ("miigunner");
INSERT into smash_character(name) VALUES ("miiswordsman");
INSERT into smash_character(name) VALUES ("ness");
INSERT into smash_character(name) VALUES ("pacman");
INSERT into smash_character(name) VALUES ("palutena");
INSERT into smash_character(name) VALUES ("peach");
INSERT into smash_character(name) VALUES ("pikachu");
INSERT into smash_character(name) VALUES ("pikmin");
INSERT into smash_character(name) VALUES ("pit");
INSERT into smash_character(name) VALUES ("robin");
INSERT into smash_character(name) VALUES ("rob");
INSERT into smash_character(name) VALUES ("rosetta");
INSERT into smash_character(name) VALUES ("roy");
INSERT into smash_character(name) VALUES ("ryu");
INSERT into smash_character(name) VALUES ("samus");
INSERT into smash_character(name) VALUES ("sheik");
INSERT into smash_character(name) VALUES ("shulk");
INSERT into smash_character(name) VALUES ("sonic");
INSERT into smash_character(name) VALUES ("toonlink");
INSERT into smash_character(name) VALUES ("villager");
INSERT into smash_character(name) VALUES ("wario");
INSERT into smash_character(name) VALUES ("wiishow fit");
INSERT into smash_character(name) VALUES ("yoshi");
INSERT into smash_character(name) VALUES ("zelda");
INSERT into smash_character(name) VALUES ("zerosuit");

INSERT into user(username, password, enabled) VALUES ("dean", "{noop}password", TRUE);
INSERT into user(username, password, enabled) VALUES ("dean2", "{noop}password", TRUE);
INSERT into user(username, password, enabled) VALUES ("dean3", "{noop}password", TRUE);
INSERT into user(username, password, enabled) VALUES ("d", "p", TRUE);

INSERT into character_notes(notes, smash_character_id, user_id) VALUES ("yo this char rox", 1, 1);
INSERT into user_character_notes(user_id, character_notes_id) VALUES (1,1);