FROM node:10 as builder

WORKDIR '/app'
COPY package*.json ./
RUN npm install
COPY . .

RUN ls -a | grep env
RUN mv .env.development .env.production
RUN ls -a | grep env
RUN cat .env.production

RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html

